name: "Optimize Resource Pack"

on:
  - push
  - pull_request

jobs:
  optimize:
    name: "Optimize Resource Pack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = "pack"
            zip_spec_conformance_level = "high"
            output_file_path = "/tmp/pack.zip"

      - name: Generate SHA-1 Hash
        uses: jmgilman/actions-generate-checksum@v1
        with:
          method: sha1
          patterns:
          - /tmp/pack.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files:
          - checksum.txt
          - /tmp/pack.zip